# YuttoPlus 默认配置文件
# 适用场景: 日常下载，平衡质量和速度

description: "默认下载配置 - 日常使用"

# === 基础设置 ===
quality: 80           # 视频质量: 1080P高清
audio_quality: 30280  # 音频质量: 320kbps
output_dir: "~/Downloads/Bilibili"  # 输出目录
format: "mp4"         # 输出格式

# === 登录设置 ===
sessdata: "eac50cae%2C1749094831%2C5a8bf%2Ac2CjAXtG6A6ADJDGdz3HyrCcFgnvEpoTd44dMDl1PfE_Vj6p6xGwdAO94TQqeW3WBhVDwSVlhXQThEYjlvRl81MmZVRGVuSk92Q3VGTHhNRDNKM21rblhwUy1keWZGQnc0N0xoelJMRlFxdzhteUNubXp4a2pyc2d2M0xrQ2llNVUzUi1HZjNxSUxnIIEC"


# === 并行设置 ===
concurrent: 1         # 并发下载数量
parallel_display: "table"  # 显示模式: table(表格) / simple(简单) / silent(静默)

# === 下载内容 ===
audio_only: false     # 是否仅下载音频
no_video: false       # 是否跳过视频
no_danmaku: false     # 是否跳过弹幕
no_cover: false       # 是否跳过封面

# === 格式设置 ===
danmaku_format: "ass" # 弹幕格式: xml / ass / protobuf
audio_format: "mp3"   # 音频格式: mp3 / wav / flac / m4a / aac
audio_bitrate: "192k" # 音频比特率
video_codec: "avc"    # 视频编码: avc / hevc / av1

# === 其他设置 ===
overwrite: false      # 是否覆盖现有文件
enable_resume: true   # 是否启用断点续传
quiet: false          # 是否使用安静模式
verbose: false        # 是否显示详细信息

# === 登录设置（可选）===
# 请填入你的B站SESSDATA，用于下载高清视频和大会员内容
# 获取方法: 登录B站 -> F12开发者工具 -> Application -> Cookies -> SESSDATA
# sessdata: "你的SESSDATA" 