# YuttoPlus 配置文件
# 适用场景: 批量下载配置 - 速度优先

description: "批量下载配置 - 速度优先"

# === 基础设置 ===
quality: 64           # 视频质量: 720P 高清
audio_quality: 30232  # 音频质量: 128kbps (标准)
output_dir: "~/Downloads/Batch_Downloads"  # 输出目录
format: "mp4"         # 输出格式

# === 并行设置 ===
concurrent: 2         # 并发下载数量
parallel_display: "table"  # 显示模式: table(表格) / simple(简单) / silent(静默)

# === 下载内容 ===
audio_only: false     # 是否仅下载音频
no_video: false       # 是否跳过视频
no_danmaku: true     # 是否跳过弹幕
no_cover: true       # 是否跳过封面

# === 格式设置 ===
danmaku_format: "ass" # 弹幕格式: xml / ass / protobuf
audio_format: "mp3"   # 音频格式: mp3 / wav / flac / m4a / aac
audio_bitrate: "192k" # 音频比特率
video_codec: "avc"    # 视频编码: avc / hevc / av1

# === 多P视频设置 ===
create_folder_for_multi_p: true  # 为多P视频创建文件夹
# episodes_selection: "1,3,5~8"  # 分P选择 (可选): 支持范围和排除语法

# === 其他设置 ===
overwrite: false      # 是否覆盖现有文件
enable_resume: true   # 是否启用断点续传
quiet: false          # 是否使用安静模式
verbose: false        # 是否显示详细信息

# === 严格验证设置 ===
vip_strict: false     # 启用严格大会员验证，非大会员时停止下载
login_strict: false   # 启用严格登录验证，未登录时停止下载

# === 登录设置（可选）===
# 请填入你的B站SESSDATA，用于下载高清视频和大会员内容
# 获取方法: 登录B站 -> F12开发者工具 -> Application -> Cookies -> SESSDATA
sessdata: "2cd08806%2C1765983164%2Ca1be6%2A62CjA6zCyinTbfVPaotT-M6TboiuE_K-BcA61Dk7SD29xcz8OBx4SD6Feg52Kj8b8UhJ8SVjg3RVpCS180VDZQUXYxT2JwbTZXM09GOFozR0FaS01sYTZOYUpqN1E5N0RoWjljSFJCWGRmYVBnY1B1Qy1QTkZnNEZjU0Y4YU56V2txMENyYmZ0bGJRIIEC"

# === 配置说明 ===
# 画质对照表:
# 127: 8K 超高清 (需要大会员，文件很大)
# 120: 4K 超清 (需要大会员，文件较大)
# 116: 1080P60 (60帧，需要大会员)
# 80:  1080P 高清 (推荐，平衡质量和大小)
# 64:  720P 高清 (较快下载，中等质量)
# 32:  480P 清晰 (快速下载，一般质量)

# 音频质量对照表:
# 30251: Hi-Res 无损 (FLAC格式，文件很大)
# 30280: 320kbps (高质量，推荐)
# 30232: 128kbps (标准质量)
# 30216: 64kbps (节省空间)